version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - npm install -g aws-cdk
  build:
    commands:
      - cdk synth ApiInfraStack -o cdk.out
artifacts:
  files:
    - cdk.out/ApiInfraStack.template.json
