version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - npm install -g aws-cdk
  build:
    commands:
      # Make Python find your local package
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - cdk synth
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'
